### ISSUE TITLE
dataset generating

### ISSUE THREAD

**Issue by mactavish91** [Heidelberg-NLP/VALSE#4]
Hello, the author, good work! Will the code you use to generate the dataset be open source?

**Comment by LetiP** [comment]
Hello @mactavish91,
Thanks for your interest in VALSE and thanks for reaching out!

As promised in the paper, we released the data and no, we do not plan to release the foil generation code. Since VALSE is a zero-shot benchmark, we think that releasing the foiling code would enable the generation of training data – which would defeat the purpose of the zero-shot benchmark.
